global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using System;
global using System.Collections.Generic;
global using Terraria;
global using Terraria.Localization;
global using Terraria.ModLoader;
global using System.Linq;
global using Terraria.ID;
global using static WeaponReset.Assets.Imgaes.MyAssets;